# Generated by Django 6.0.6 on 2026-06-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='semester',
            new_name='intake',
        ),
    ]
