# Generated by Django 6.0.6 on 2026-06-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_semester_user_intake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='intake',
        ),
    ]
