# Generated by Django 6.0.6 on 2026-06-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('senior_student', 'Senior Student'), ('club_authority', 'Club Authority'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
