# Generated by Django 6.0.6 on 2026-06-06 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_blocked_user_login_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('notes', 'Notes Repository'), ('ct_questions', 'CT Question Bank'), ('lab_cover', 'Lab Cover Generator'), ('assignment_cover', 'Assignment Cover'), ('jobs', 'Job & Internship Board'), ('blood_donation', 'Blood Donation'), ('clubs_events', 'Club & Events'), ('lost_found', 'Lost & Found'), ('book_marketplace', 'Book Marketplace'), ('emergency', 'Emergency Contacts')], max_length=30)),
                ('is_allowed', models.BooleanField(default=True)),
                ('daily_limit', models.PositiveIntegerField(default=0, help_text='0 means unlimited daily usage')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='feature_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['feature_key'],
                'unique_together': {('student', 'feature_key')},
            },
        ),
    ]
