# Generated by Django 6.0.6 on 2026-08-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_bio_user_blood_group_user_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='verification/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='verification/'),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
