# Generated by Django 6.0.6 on 2026-08-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_status_event_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('technology', 'Technology'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('business', 'Business'), ('social', 'Social'), ('volunteer', 'Volunteer'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='seat_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closing_soon', 'Closing Soon'), ('full', 'Full'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('executive', 'Executive Member'), ('vice_president', 'Vice President'), ('president', 'President'), ('advisor', 'Advisor'), ('admin', 'Admin')], default='member', max_length=20),
        ),
    ]
