# Generated by Django 6.0.6 on 2026-08-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_clubapplication_unique_together_clubadminclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubadminclaim',
            name='role_claimed',
            field=models.CharField(default='President', max_length=100),
        ),
    ]
