# Generated by Django 6.0.6 on 2026-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubadminclaim',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/claims/'),
        ),
        migrations.AlterField(
            model_name='clubadminclaim',
            name='proof',
            field=models.TextField(blank=True, null=True),
        ),
    ]
