# Generated by Django 6.0.6 on 2026-08-08 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_points', models.IntegerField(default=0)),
                ('career_points', models.IntegerField(default=0)),
                ('club_points', models.IntegerField(default=0)),
                ('community_points', models.IntegerField(default=0)),
                ('marketplace_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('career', 'Career'), ('club', 'Club & Events'), ('community', 'Community'), ('marketplace', 'Marketplace')], max_length=20)),
                ('action_name', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
