# Generated by Django 6.0.6 on 2026-08-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='listing_type',
            field=models.CharField(choices=[('sell', 'Selling'), ('buy', 'Looking to Buy')], default='sell', max_length=10),
        ),
    ]
