# Generated by Django 5.1.4 on 2026-08-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_marketplaceitem_date_lost_found_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceitem',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
