# Generated by Django 6.0.6 on 2026-06-05 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('BBA', 'BBA'), ('English', 'English'), ('Civil', 'Civil'), ('Architecture', 'Architecture'), ('Law', 'Law')], default=71, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='intake',
            field=models.CharField(choices=[('71', '71'), ('72', '72'), ('73', '73'), ('74', '74'), ('75', '75'), ('76', '76'), ('77', '77'), ('78', '78')], max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
