# Generated by Django 6.0.6 on 2026-06-06 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_ctquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('internship', 'Internship'), ('full_time', 'Full-time Job'), ('part_time', 'Part-time'), ('freelance', 'Freelance')], max_length=20)),
                ('department', models.CharField(blank=True, choices=[('', 'All Departments'), ('CSE', 'CSE'), ('EEE', 'EEE'), ('BBA', 'BBA'), ('English', 'English'), ('Civil', 'Civil'), ('Architecture', 'Architecture'), ('Law', 'Law')], default='', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('work_mode', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', max_length=20)),
                ('salary_range', models.CharField(blank=True, max_length=120)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('apply_link', models.URLField(blank=True)),
                ('apply_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
