# Generated by Django 6.0.6 on 2026-06-07 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='blood_donor_photos/')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, help_text='Weight in kg', null=True)),
                ('division', models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong'), ('sylhet', 'Sylhet'), ('rajshahi', 'Rajshahi'), ('khulna', 'Khulna'), ('barisal', 'Barisal'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh')], max_length=30)),
                ('district', models.CharField(blank=True, max_length=60)),
                ('upazila', models.CharField(blank=True, max_length=60)),
                ('address', models.TextField(blank=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('emergency_available', models.BooleanField(default=False)),
                ('medical_notes', models.TextField(blank=True)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-emergency_available', '-total_donations', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('bags_needed', models.PositiveSmallIntegerField(default=1)),
                ('hospital_name', models.CharField(max_length=200)),
                ('hospital_location', models.CharField(blank=True, max_length=200)),
                ('division', models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong'), ('sylhet', 'Sylhet'), ('rajshahi', 'Rajshahi'), ('khulna', 'Khulna'), ('barisal', 'Barisal'), ('rangpur', 'Rangpur'), ('mymensingh', 'Mymensingh')], max_length=30)),
                ('district', models.CharField(blank=True, max_length=60)),
                ('contact_person', models.CharField(max_length=120)),
                ('contact_number', models.CharField(max_length=20)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('urgent', 'Urgent'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=15)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('story', 'Donation Story'), ('awareness', 'Awareness'), ('request', 'Request Share')], default='story', max_length=15)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blood_posts/')),
                ('comments', models.JSONField(default=list)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_blood_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_to', models.CharField(blank=True, max_length=120)),
                ('hospital', models.CharField(blank=True, max_length=200)),
                ('donation_date', models.DateField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('bags', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_records', to='blood_donation.blooddonor')),
            ],
            options={
                'ordering': ['-donation_date'],
            },
        ),
    ]
